# Generated by Django 6.0.1 on 2026-02-18 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobapplication'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scamreport',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='scamreport',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scamreport',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scamreport',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scam_reports', to='jobs.job'),
        ),
        migrations.AlterField(
            model_name='scamreport',
            name='reason',
            field=models.CharField(choices=[('scam', 'Fake Job / Scam'), ('money', 'Requesting Payment/Bank Details'), ('off_platform', 'Asking to communicate off-platform'), ('offensive', 'Inappropriate or Offensive Content'), ('other', 'Other / General Suspicion')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='scamreport',
            unique_together={('job', 'reported_by')},
        ),
    ]
